# Generated by Django 4.2 on 2023-04-26 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='game',
            new_name='question',
        ),
    ]
