# Generated by Django 4.2 on 2023-06-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_authuser_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='correct_ans',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='history',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='history',
            name='question',
            field=models.CharField(max_length=100),
        ),
    ]
